# https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts
import logging
import struct

from midi2mkcd.arcade.music_types import (
    LFO,
    DrumInstrument,
    DrumSoundStep,
    EnharmonicSpelling,
    Envelope,
    Instrument,
    Note,
    NoteEvent,
    Song,
    Track,
)
from midi2mkcd.utils.logger import create_logger

logger = create_logger(name=__name__, level=logging.INFO)


def set_8_bit_number(buf: bytearray, offset: int, value: int) -> None:
    struct.pack_into("<B", buf, offset, value & 0xFF)


def get_8_bit_number(buf: bytearray, offset: int) -> int:
    return struct.unpack_from("<B", buf, offset)[0]


def set_16_bit_number(buf: bytearray, offset: int, value: int) -> None:
    struct.pack_into("<H", buf, offset, value & 0xFFFF)


def get_16_bit_number(buf: bytearray, offset: int) -> int:
    return struct.unpack_from("<H", buf, offset)[0]


def encode_song_to_hex(song: Song) -> str:
    """
    Encode a MakeCode Arcade song into a hex string. Surround this hex string with
    hex` and ` to create a valid MakeCode Arcade TypeScript buffer for MakeCode Arcade
    to use.

    :param song: The MakeCode Arcade song.
    :return: A hex representation of the bytearray that is generated by
     `encode_song(song)`.
    """
    encoded = encode_song(song)
    return "".join(f"{byte:02X}" for byte in encoded)


def encode_song(song: Song) -> bytearray:
    """
    Encode a MakeCode Arcade song into a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L96

    :param song: The MakeCode Arcade song.
    :return: A bytearray, convert this to hex to use in a MakeCode Arcade program.
    """
    encoded_tracks = [
        encode_track(track) for track in song.tracks if len(track.notes) > 0
    ]
    encoded_track_velocities: list[bytearray] = list(
        filter(
            lambda v: v is not None,
            [encode_track_velocity(track) for track in song.tracks],
        )
    )

    track_length = sum(len(c) for c in (encoded_tracks + encoded_track_velocities))

    out = bytearray(7 + track_length)
    set_8_bit_number(out, 0, 0)  # encoding version
    set_16_bit_number(out, 1, song.beats_per_minute)
    set_8_bit_number(out, 3, song.beats_per_measure)
    set_8_bit_number(out, 4, song.ticks_per_beat)
    set_8_bit_number(out, 5, song.measures)
    set_8_bit_number(out, 6, len(encoded_tracks))

    current = 7
    for track in encoded_tracks:
        out[current : current + len(track)] = track
        current += len(track)

    for trackVelocity in encoded_track_velocities:
        out[current : current + len(trackVelocity)] = trackVelocity
        current += len(trackVelocity)

    return out


def encode_instrument(instrument: Instrument) -> bytearray:
    """
    Encode a MakeCode Arcade instrument into a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L127

    :param instrument: The MakeCode Arcade instrument.
    :return: A bytearray.
    """
    out = bytearray(28)
    set_8_bit_number(out, 0, instrument.waveform)
    set_16_bit_number(out, 1, instrument.amp_envelope.attack)
    set_16_bit_number(out, 3, instrument.amp_envelope.decay)
    set_16_bit_number(out, 5, instrument.amp_envelope.sustain)
    set_16_bit_number(out, 7, instrument.amp_envelope.release)
    set_16_bit_number(out, 9, instrument.amp_envelope.amplitude)
    if instrument.pitch_envelope is not None:
        set_16_bit_number(out, 11, instrument.pitch_envelope.attack)
        set_16_bit_number(out, 13, instrument.pitch_envelope.decay)
        set_16_bit_number(out, 15, instrument.pitch_envelope.sustain)
        set_16_bit_number(out, 17, instrument.pitch_envelope.release)
        set_16_bit_number(out, 19, instrument.pitch_envelope.amplitude)
    else:
        set_16_bit_number(out, 11, 0)
        set_16_bit_number(out, 13, 0)
        set_16_bit_number(out, 15, 0)
        set_16_bit_number(out, 17, 0)
        set_16_bit_number(out, 19, 0)
    if instrument.amp_lfo is not None:
        set_8_bit_number(out, 21, instrument.amp_lfo.frequency)
        set_16_bit_number(out, 22, instrument.amp_lfo.amplitude)
    else:
        set_8_bit_number(out, 21, 0)
        set_16_bit_number(out, 22, 0)
    if instrument.pitch_lfo is not None:
        set_8_bit_number(out, 24, instrument.pitch_lfo.frequency)
        set_16_bit_number(out, 25, instrument.pitch_lfo.amplitude)
    else:
        set_8_bit_number(out, 24, 0)
        set_16_bit_number(out, 25, 0)
    set_8_bit_number(out, 27, instrument.octave if instrument.octave is not None else 0)
    return out


def encode_drum_instrument(drum: DrumInstrument) -> bytearray:
    """
    Encode a MakeCode Arcade drum instrument into a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L149

    :param drum: The MakeCode Arcade drum instrument.
    :return: A bytearray.
    """
    out = bytearray(5 + 7 * len(drum.steps))
    set_8_bit_number(out, 0, len(drum.steps))
    set_16_bit_number(out, 1, drum.start_frequency)
    set_16_bit_number(out, 3, drum.start_volume)
    for i, step in enumerate(drum.steps):
        start = 5 + i * 7
        set_8_bit_number(out, start, step.waveform)
        set_16_bit_number(out, start + 1, step.frequency)
        set_16_bit_number(out, start + 3, step.volume)
        set_16_bit_number(out, start + 5, step.duration)
    return out


def encode_note_event(
    event: NoteEvent, instrument_octave: int, is_drum_track: bool
) -> bytearray:
    """
    Encode a MakeCode Arcade note event into a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L166

    :param event: The MakeCode Arcade `NoteEvent`.
    :param instrument_octave: The instrument octave offset used for the note event.
    :param is_drum_track: Whether this note event is for a drum track or not.
    :return: A bytearray.
    """
    out = bytearray(5 + len(event.notes))
    set_16_bit_number(out, 0, event.start_tick)
    set_16_bit_number(out, 2, event.end_tick)
    set_8_bit_number(out, 4, len(event.notes))

    for i, note in enumerate(event.notes):
        set_8_bit_number(
            out, 5 + i, encode_note(note, instrument_octave, is_drum_track)
        )

    return out


def encode_note(note: Note, instrument_octave: int, is_drum_track: bool) -> int:
    """
    Encode a MakeCode Arcade note into a single byte. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L179

    :param note: The MakeCode Arcade `Note`.
    :param instrument_octave: The instrument octave offset used for the note.
    :param is_drum_track: Whether this note is for a drum track or not.
    :return: An int, which will fit into a single byte.
    """
    if is_drum_track:
        return note.note

    flags = 0
    if note.enharmonic_spelling == EnharmonicSpelling.FLAT:
        flags = 1
    elif note.enharmonic_spelling == EnharmonicSpelling.SHARP:
        flags = 2

    return (note.note - (instrument_octave - 2) * 12) | (flags << 6)


def encode_track(track: Track) -> bytearray:
    """
    Encode a MakeCode Arcade track into a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L195

    :param track: The MakeCode Arcade `Track`.
    :return: A bytearray.
    """
    if track.drums:
        return encode_drum_track(track)
    else:
        return encode_melodic_track(track)


def encode_track_velocity(track: Track) -> bytearray | None:
    """
    Encode a MakeCode Arcade track's velocity data into a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L200

    :param track: The MakeCode Arcade `Track`.
    :return: A bytearray.
    """
    if not any(
        note.velocity is not None and note.velocity < 128 for note in track.notes
    ):
        return None

    out = bytearray(1 + len(track.notes))
    set_8_bit_number(out, 0, track.id)
    for i, note in enumerate(track.notes):
        set_8_bit_number(out, 1 + i, note.velocity if note.velocity is not None else 0)
    return out


def encode_melodic_track(track: Track) -> bytearray:
    """
    Encode a MakeCode Arcade melodic track into a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L211

    :param track: The MakeCode Arcade `Track`, must be melodic.
    :return: A bytearray.
    """
    encoded_instrument = encode_instrument(track.instrument)
    encoded_notes = [
        encode_note_event(note, track.instrument.octave, False) for note in track.notes
    ]
    note_length = sum(len(c) for c in encoded_notes)

    out = bytearray(6 + len(encoded_instrument) + note_length)
    set_8_bit_number(out, 0, track.id)
    set_8_bit_number(out, 1, 0)

    set_16_bit_number(out, 2, len(encoded_instrument))
    current = 4
    out[current : current + len(encoded_instrument)] = encoded_instrument
    current += len(encoded_instrument)

    set_16_bit_number(out, current, note_length)
    current += 2
    for note in encoded_notes:
        out[current : current + len(note)] = note
        current += len(note)

    return out


def encode_drum_track(track: Track) -> bytearray:
    """
    Encode a MakeCode Arcade drum track into a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L235

    :param track: The MakeCode Arcade `Track`, must be a drum track.
    :return: A bytearray.
    """
    assert track.drums is not None
    encoded_drums = [encode_drum_instrument(drum) for drum in track.drums]
    drum_length = sum(len(c) for c in encoded_drums)

    encoded_notes = [encode_note_event(note, 0, True) for note in track.notes]
    note_length = sum(len(c) for c in encoded_notes)

    out = bytearray(6 + drum_length + note_length)
    set_8_bit_number(out, 0, track.id)
    set_8_bit_number(out, 1, 1)
    set_16_bit_number(out, 2, drum_length)
    current = 4

    for drum in encoded_drums:
        out[current : current + len(drum)] = drum
        current += len(drum)

    set_16_bit_number(out, current, note_length)
    current += 2
    for note in encoded_notes:
        out[current : current + len(note)] = note
        current += len(note)

    return out


def decode_song_from_hex(hex: str) -> Song:
    """
    Decode a MakeCode Arcade song from a hex string. The parts "hex`" and "`" before and
    after a typical MakeCode Arcade TypeScript buffer must have been removed before
    using this function.

    :param hex: The bare hex buffer of the MakeCode Arcade song.
    :return: A MakeCode Arcade `Song` that is generated by `decode_song(buf)`.
    """
    buf = bytearray.fromhex(hex)
    return decode_song(buf)


def decode_song(buf: bytearray) -> Song:
    """
    Decode a MakeCode Arcade song from a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L269

    :param buf: A bytearray of an entire song.
    :return: A MakeCode Arcade `Song`.
    """
    res = Song(
        beats_per_minute=get_16_bit_number(buf, 1),
        beats_per_measure=get_8_bit_number(buf, 3),
        ticks_per_beat=get_8_bit_number(buf, 4),
        measures=get_8_bit_number(buf, 5),
        tracks=[],
    )

    num_tracks = get_8_bit_number(buf, 6)
    current = 7

    for _ in range(num_tracks):
        track, pointer = decode_track(buf, current)
        current = pointer
        res.tracks.append(track)

    while current < len(buf):
        current = decode_track_velocity(buf, res.tracks, current)

    return res


def decode_instrument(buf: bytearray, offset: int) -> Instrument:
    """
    Decode a MakeCode Arcade instrument from a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L294

    :param buf: A bytearray of an entire song.
    :param offset: The offset in the bytearray which to start reading the instrument
     data from.
    :return: A MakeCode Arcade `Instrument`.
    """
    return Instrument(
        waveform=get_8_bit_number(buf, offset),
        amp_envelope=Envelope(
            attack=get_16_bit_number(buf, offset + 1),
            decay=get_16_bit_number(buf, offset + 3),
            sustain=get_16_bit_number(buf, offset + 5),
            release=get_16_bit_number(buf, offset + 7),
            amplitude=get_16_bit_number(buf, offset + 9),
        ),
        pitch_envelope=Envelope(
            attack=get_16_bit_number(buf, offset + 11),
            decay=get_16_bit_number(buf, offset + 13),
            sustain=get_16_bit_number(buf, offset + 15),
            release=get_16_bit_number(buf, offset + 17),
            amplitude=get_16_bit_number(buf, offset + 19),
        ),
        amp_lfo=LFO(
            frequency=get_8_bit_number(buf, offset + 21),
            amplitude=get_16_bit_number(buf, offset + 22),
            # the original implementation is 22 instead of offset + 22
        ),
        pitch_lfo=LFO(
            frequency=get_8_bit_number(buf, offset + 24),
            amplitude=get_16_bit_number(buf, offset + 25),
            # the original implementation is 25 instead of offset + 25
        ),
        octave=get_8_bit_number(buf, offset + 27),
    )


def decode_track(buf: bytearray, offset: int) -> tuple[Track, int]:
    """
    Decode a MakeCode Arcade track from a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L323

    :param buf: A bytearray of an entire song.
    :param offset: The offset in the bytearray which to start reading the track
     data from.
    :return: A MakeCode Arcade `Track`.
    """
    if get_8_bit_number(buf, offset + 1) != 0:
        return decode_drum_track(buf, offset)
    else:
        return decode_melodic_track(buf, offset)


def decode_track_velocity(buf: bytearray, tracks: list[Track], offset: int) -> int:
    """
    Decode a MakeCode Arcade track velocity from a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L331

    :param buf: A bytearray of an entire song.
    :param tracks: A list of `Track` objects which have already been decoded from the
     bytearray, the one with the matching ID will have the note velocities set.
    :param offset: The offset in the bytearray which to start reading the track velocity
     data from.
    :return: The next offset after the end of this track velocity data.
    """
    track_id = get_8_bit_number(buf, offset)
    track = next((t for t in tracks if t.id == track_id), None)
    if track is None:
        raise ValueError(f"Track with {track_id} not found")
    for i in range(len(track.notes)):
        track.notes[i].velocity = get_8_bit_number(buf, offset + i + 1)
    return offset + len(track.notes) + 1


def decode_drum_instrument(buf: bytearray, offset: int) -> DrumInstrument:
    """
    Decode a MakeCode Arcade drum instrument from a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L341

    :param buf: A bytearray of an entire song.
    :param offset: The offset in the bytearray which to start reading the drum
     instrument data from.
    :return: A MakeCode Arcade `DrumInstrument`.
    """
    res = DrumInstrument(
        start_frequency=get_16_bit_number(buf, offset + 1),
        start_volume=get_16_bit_number(buf, offset + 3),
        steps=[],
    )

    for i in range(get_8_bit_number(buf, offset)):
        start = offset + 5 + i * 7
        res.steps.append(
            DrumSoundStep(
                waveform=get_8_bit_number(buf, start),
                frequency=get_16_bit_number(buf, start + 1),
                volume=get_16_bit_number(buf, start + 3),
                duration=get_16_bit_number(buf, start + 5),
            )
        )

    return res


def decode_note_event(
    buf: bytearray, offset: int, instrument_octave: int, is_drum_track: bool
) -> NoteEvent:
    """
    Decode a MakeCode Arcade note event from a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L361

    :param buf: A bytearray of an entire song.
    :param offset: The offset in the bytearray which to start reading the note event
     data from.
    :param instrument_octave: The instrument's octave offset used for the note event,
     needed to decode the note value itself.
    :param is_drum_track: Whether this note event is for a drum track or not, needed to
     decode the note.
    :return: A MakeCode Arcade `NoteEvent`.
    """
    res = NoteEvent(
        start_tick=get_16_bit_number(buf, offset),
        end_tick=get_16_bit_number(buf, offset + 2),
        notes=[],
    )

    for i in range(get_8_bit_number(buf, offset + 4)):
        res.notes.append(
            decode_note(
                get_8_bit_number(buf, offset + 5 + i), instrument_octave, is_drum_track
            )
        )

    return res


def decode_note(note: int, instrument_octave: int, is_drum_track: bool) -> Note:
    """
    Construct a MakeCode Arcade note from specified parameters. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L374

    :param note: The note number itself, between 0 and 63. For melodic tracks, the
     instrument octave is taken into account.
    :param instrument_octave: The track's instrument's octave offset.
    :param is_drum_track: Whether this note is for a drum track or not.
    :return: A MakeCode Arcade `Note`.
    """
    flags = note >> 6
    res = Note(
        note=note if is_drum_track else ((note & 0x3F) + (instrument_octave - 2) * 12),
        enharmonic_spelling=EnharmonicSpelling.NORMAL,
    )

    if flags == 1:
        res.enharmonic_spelling = EnharmonicSpelling.FLAT
    elif flags == 2:
        res.enharmonic_spelling = EnharmonicSpelling.SHARP

    return res


def decode_melodic_track(buf: bytearray, offset: int) -> tuple[Track, int]:
    """
    Decode a MakeCode Arcade melodic track from a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L392

    :param buf: A bytearray of an entire song.
    :param offset: The offset in the bytearray which to start reading the melodic track
     data from.
    :return: A tuple of a MakeCode Arcade `Track` and the next offset after the end of
     this track data.
    """
    res = Track(
        id=get_8_bit_number(buf, offset),
        instrument=decode_instrument(buf, offset + 4),
        notes=[],
    )

    note_start = offset + 4 + get_16_bit_number(buf, offset + 2)
    note_length = get_16_bit_number(buf, note_start)

    current_offset = note_start + 2

    while current_offset < note_start + 2 + note_length:
        res.notes.append(
            decode_note_event(buf, current_offset, res.instrument.octave, False)
        )
        current_offset += 5 + len(res.notes[-1].notes)

    return res, current_offset


def decode_drum_track(buf: bytearray, offset: int) -> tuple[Track, int]:
    """
    Decode a MakeCode Arcade drum track from a bytearray. Ported from
    https://github.com/microsoft/pxt/blob/master/pxtlib/music.ts#L412

    :param buf: A bytearray of an entire song.
    :param offset: The offset in the bytearray which to start reading the drum track
     data from.
    :return: A tuple of a MakeCode Arcade `Track` and the next offset after the end of
     this track data.
    """
    res = Track(
        id=get_8_bit_number(buf, offset),
        instrument=Instrument(
            amp_envelope=Envelope(attack=0, decay=0, sustain=0, release=0, amplitude=0),
            waveform=0,
            octave=0,
        ),
        notes=[],
        drums=[],
    )

    drum_byte_length = get_16_bit_number(buf, offset + 2)
    current_offset = offset + 4

    while current_offset < (offset + 4 + drum_byte_length):
        res.drums.append(decode_drum_instrument(buf, current_offset))
        current_offset += 5 + 7 * len(res.drums[-1].steps)

    note_length = get_16_bit_number(buf, current_offset)
    current_offset += 2

    while current_offset < (offset + 4 + drum_byte_length + note_length):
        res.notes.append(decode_note_event(buf, current_offset, 0, True))
        current_offset += 5 + len(res.notes[-1].notes)

    return res, current_offset


def get_empty_song(measures: int) -> Song:
    """
    Generate an empty MakeCode Arcade song with the specified number of measures,
    including the default instruments.

    :param measures: The number of measures to include.
    :return: A MakeCode Arcade `Song`.
    """
    tracks: list[Track] = [
        Track(
            id=0,
            name="Dog",
            notes=[],
            icon_uri="music-editor/dog.png",
            instrument=Instrument(
                waveform=1,
                octave=4,
                amp_envelope=Envelope(
                    attack=10, decay=100, sustain=500, release=100, amplitude=1024
                ),
                pitch_envelope=None,
                amp_lfo=None,
                pitch_lfo=LFO(frequency=5, amplitude=0),
            ),
        ),
        Track(
            id=1,
            name="Duck",
            notes=[],
            icon_uri="music-editor/duck.png",
            instrument=Instrument(
                waveform=15,
                octave=4,
                amp_envelope=Envelope(
                    attack=5, decay=530, sustain=705, release=450, amplitude=1024
                ),
                pitch_envelope=Envelope(
                    attack=5, decay=40, sustain=0, release=100, amplitude=40
                ),
                amp_lfo=LFO(frequency=3, amplitude=20),
                pitch_lfo=LFO(frequency=6, amplitude=2),
            ),
        ),
        Track(
            id=2,
            name="Cat",
            notes=[],
            icon_uri="music-editor/cat.png",
            instrument=Instrument(
                waveform=12,
                octave=5,
                amp_envelope=Envelope(
                    attack=150, decay=100, sustain=365, release=400, amplitude=1024
                ),
                pitch_envelope=Envelope(
                    attack=120, decay=300, sustain=0, release=100, amplitude=50
                ),
                amp_lfo=None,
                pitch_lfo=LFO(frequency=10, amplitude=6),
            ),
        ),
        Track(
            id=3,
            name="Fish",
            notes=[],
            icon_uri="music-editor/fish.png",
            instrument=Instrument(
                waveform=1,
                octave=3,
                amp_envelope=Envelope(
                    attack=220, decay=105, sustain=1024, release=350, amplitude=1024
                ),
                amp_lfo=LFO(frequency=5, amplitude=100),
                pitch_lfo=LFO(frequency=1, amplitude=4),
                pitch_envelope=None,
            ),
        ),
        Track(
            id=4,
            name="Car",
            notes=[],
            icon_uri="music-editor/car.png",
            instrument=Instrument(
                waveform=16,
                octave=4,
                amp_envelope=Envelope(
                    attack=5, decay=100, sustain=1024, release=30, amplitude=1024
                ),
                pitch_lfo=LFO(frequency=10, amplitude=4),
                pitch_envelope=None,
                amp_lfo=None,
            ),
        ),
        Track(
            id=5,
            name="Computer",
            notes=[],
            icon_uri="music-editor/computer.png",
            instrument=Instrument(
                waveform=15,
                octave=2,
                amp_envelope=Envelope(
                    attack=10, decay=100, sustain=500, release=10, amplitude=1024
                ),
            ),
        ),
        Track(
            id=6,
            name="Burger",
            notes=[],
            icon_uri="music-editor/burger.png",
            instrument=Instrument(
                waveform=1,
                octave=2,
                amp_envelope=Envelope(
                    attack=10, decay=100, sustain=500, release=100, amplitude=1024
                ),
            ),
        ),
        Track(
            id=7,
            name="Cherry",
            notes=[],
            icon_uri="music-editor/cherry.png",
            instrument=Instrument(
                waveform=2,
                octave=3,
                amp_envelope=Envelope(
                    attack=10, decay=100, sustain=500, release=100, amplitude=1024
                ),
            ),
        ),
        Track(
            id=8,
            name="Lemon",
            notes=[],
            icon_uri="music-editor/lemon.png",
            instrument=Instrument(
                waveform=14,
                octave=2,
                amp_envelope=Envelope(
                    attack=5, decay=70, sustain=870, release=50, amplitude=1024
                ),
                pitch_envelope=Envelope(
                    attack=10, decay=45, sustain=0, release=100, amplitude=20
                ),
                amp_lfo=LFO(frequency=1, amplitude=50),
                pitch_lfo=LFO(frequency=2, amplitude=1),
            ),
        ),
        Track(
            id=9,
            name="Drums",
            notes=[],
            icon_uri="music-editor/explosion.png",
            instrument=Instrument(
                waveform=11,
                octave=4,
                amp_envelope=Envelope(
                    attack=10, decay=100, sustain=500, release=100, amplitude=1024
                ),
            ),
            drums=[
                DrumInstrument(
                    name="neutral kick",
                    start_frequency=100,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=3, frequency=120, duration=10, volume=1024
                        ),
                        DrumSoundStep(waveform=3, frequency=1, duration=100, volume=0),
                    ],
                ),
                DrumInstrument(
                    name="punchy kick",
                    start_frequency=200,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(waveform=1, frequency=0, duration=100, volume=0)
                    ],
                ),
                DrumInstrument(
                    name="booming kick",
                    start_frequency=100,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(waveform=1, frequency=0, duration=250, volume=0)
                    ],
                ),
                DrumInstrument(
                    name="snare 1",
                    start_frequency=175,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=1, frequency=200, duration=10, volume=1024
                        ),
                        DrumSoundStep(
                            waveform=1, frequency=150, duration=20, volume=1024
                        ),
                        DrumSoundStep(waveform=5, frequency=1, duration=20, volume=100),
                        DrumSoundStep(waveform=5, frequency=1, duration=300, volume=0),
                    ],
                ),
                DrumInstrument(
                    name="snare 2",
                    start_frequency=220,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=1, frequency=250, duration=10, volume=1024
                        ),
                        DrumSoundStep(
                            waveform=1, frequency=200, duration=20, volume=1024
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=2000, duration=20, volume=100
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=2000, duration=200, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="hat 1",
                    start_frequency=400,
                    start_volume=500,
                    steps=[
                        DrumSoundStep(
                            waveform=5, frequency=450, duration=10, volume=500
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=400, duration=20, volume=20
                        ),
                    ],
                ),
                DrumInstrument(
                    name="hat 2",
                    start_frequency=400,
                    start_volume=0,
                    steps=[
                        DrumSoundStep(
                            waveform=5, frequency=450, duration=5, volume=500
                        ),
                        DrumSoundStep(waveform=5, frequency=900, duration=50, volume=5),
                        DrumSoundStep(
                            waveform=5, frequency=900, duration=250, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="hat 3",
                    start_frequency=400,
                    start_volume=0,
                    steps=[
                        DrumSoundStep(
                            waveform=5, frequency=450, duration=5, volume=500
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=900, duration=50, volume=200
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=900, duration=100, volume=5
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=900, duration=400, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="hat 4",
                    start_frequency=400,
                    start_volume=0,
                    steps=[
                        DrumSoundStep(
                            waveform=5, frequency=450, duration=5, volume=500
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=900, duration=100, volume=200
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=900, duration=200, volume=5
                        ),
                        DrumSoundStep(
                            waveform=5, frequency=900, duration=500, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="double hat",
                    start_frequency=3500,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=4, frequency=4000, duration=10, volume=0
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=3500, duration=1, volume=800
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=4000, duration=40, volume=0
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=3500, duration=1, volume=400
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=4000, duration=40, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="metallic",
                    start_frequency=2000,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=4, frequency=1800, duration=100, volume=15
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=1800, duration=200, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="low tom",
                    start_frequency=200,
                    start_volume=200,
                    steps=[
                        DrumSoundStep(
                            waveform=14, frequency=125, duration=25, volume=200
                        ),
                        DrumSoundStep(
                            waveform=14, frequency=100, duration=50, volume=15
                        ),
                        DrumSoundStep(
                            waveform=14, frequency=120, duration=250, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="mid tom",
                    start_frequency=300,
                    start_volume=200,
                    steps=[
                        DrumSoundStep(
                            waveform=14, frequency=225, duration=25, volume=200
                        ),
                        DrumSoundStep(
                            waveform=14, frequency=200, duration=50, volume=15
                        ),
                        DrumSoundStep(
                            waveform=14, frequency=220, duration=250, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="hi tom",
                    start_frequency=500,
                    start_volume=200,
                    steps=[
                        DrumSoundStep(
                            waveform=14, frequency=425, duration=25, volume=200
                        ),
                        DrumSoundStep(
                            waveform=14, frequency=400, duration=50, volume=15
                        ),
                        DrumSoundStep(
                            waveform=14, frequency=420, duration=250, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="lo tom 2",
                    start_frequency=200,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(waveform=1, frequency=75, duration=200, volume=0),
                    ],
                ),
                DrumInstrument(
                    name="mid tom 2",
                    start_frequency=300,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=1, frequency=200, duration=200, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="hi tom 2",
                    start_frequency=400,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=1, frequency=300, duration=200, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="thump 1",
                    start_frequency=200,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=4, frequency=200, duration=100, volume=15
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=150, duration=200, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="thump 2",
                    start_frequency=450,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=4, frequency=350, duration=100, volume=15
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=300, duration=100, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="cymbal",
                    start_frequency=2500,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=4, frequency=2500, duration=150, volume=100
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=2550, duration=500, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="crash 1",
                    start_frequency=3000,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=4, frequency=3000, duration=300, volume=100
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=3060, duration=500, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="crash 2",
                    start_frequency=800,
                    start_volume=0,
                    steps=[
                        DrumSoundStep(
                            waveform=4, frequency=800, duration=10, volume=1024
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=800, duration=490, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="crash 3",
                    start_frequency=400,
                    start_volume=0,
                    steps=[
                        DrumSoundStep(
                            waveform=4, frequency=400, duration=10, volume=1024
                        ),
                        DrumSoundStep(
                            waveform=4, frequency=400, duration=400, volume=0
                        ),
                    ],
                ),
                DrumInstrument(
                    name="buzzer",
                    start_frequency=2000,
                    start_volume=1024,
                    steps=[
                        DrumSoundStep(
                            waveform=16, frequency=2000, duration=150, volume=100
                        ),
                        DrumSoundStep(
                            waveform=16, frequency=2000, duration=200, volume=0
                        ),
                    ],
                ),
            ],
        ),
    ]

    return Song(
        measures=measures,
        beats_per_measure=4,
        beats_per_minute=120,
        ticks_per_beat=8,
        tracks=tracks,
    )
